services:
  - type: web
    name: doller-backend
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7000
      - key: CLIENT_URL
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        value: 3306
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: REDIS_ENABLED
        value: true
      - key: REDIS_URL
        value: redis://127.0.0.1:6379
      - key: MEMORY_CACHE_MAX_KEYS
        value: 5000
      - key: ENABLE_QUEUE
        value: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
