CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  mongo_id VARCHAR(24) NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(254) NULL,
  email_lower VARCHAR(254) NULL,
  phone VARCHAR(20) NULL,
  phone_normalized VARCHAR(15) NULL,
  provider ENUM('email', 'google', 'github') NOT NULL DEFAULT 'email',
  password VARCHAR(255) NULL,
  role ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  email_verified TINYINT(1) NOT NULL DEFAULT 0,
  phone_verified TINYINT(1) NOT NULL DEFAULT 0,
  is_verified TINYINT(1) NOT NULL DEFAULT 0,
  google_id VARCHAR(191) NULL,
  github_id VARCHAR(191) NULL,
  avatar VARCHAR(500) NOT NULL DEFAULT '',
  token_version INT UNSIGNED NOT NULL DEFAULT 0,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_mongo_id (mongo_id),
  UNIQUE KEY uq_users_email_lower (email_lower),
  UNIQUE KEY uq_users_phone_normalized (phone_normalized),
  UNIQUE KEY uq_users_google_id (google_id),
  UNIQUE KEY uq_users_github_id (github_id),
  KEY idx_users_role_deleted_created (role, is_deleted, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mysql_documents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  collection_name VARCHAR(80) NOT NULL,
  mongo_id VARCHAR(24) NOT NULL,
  data JSON NOT NULL,
  doc_email VARCHAR(254) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(data, '$.email'))) STORED,
  doc_email_lower VARCHAR(254) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(data, '$.emailLower'))) STORED,
  doc_slug VARCHAR(220) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(data, '$.slug'))) STORED,
  doc_user_id VARCHAR(24) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(data, '$.userId'))) STORED,
  doc_status VARCHAR(60) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(data, '$.status'))) STORED,
  doc_role VARCHAR(40) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(data, '$.role'))) STORED,
  doc_is_deleted TINYINT(1) GENERATED ALWAYS AS (
    CASE JSON_UNQUOTE(JSON_EXTRACT(data, '$.isDeleted')) WHEN 'true' THEN 1 WHEN '1' THEN 1 ELSE 0 END
  ) STORED,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mysql_documents_collection_id (collection_name, mongo_id),
  KEY idx_mysql_documents_collection (collection_name),
  KEY idx_mysql_documents_email (collection_name, doc_email),
  KEY idx_mysql_documents_email_lower (collection_name, doc_email_lower),
  KEY idx_mysql_documents_slug (collection_name, doc_slug),
  KEY idx_mysql_documents_user (collection_name, doc_user_id),
  KEY idx_mysql_documents_status (collection_name, doc_status),
  KEY idx_mysql_documents_role_deleted (collection_name, doc_role, doc_is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  mongo_id VARCHAR(24) NULL,
  name VARCHAR(80) NOT NULL,
  slug VARCHAR(120) NOT NULL,
  gender ENUM('men', 'women') NOT NULL,
  type ENUM('top', 'bottom', 'other') NOT NULL,
  sizes JSON NULL,
  description VARCHAR(500) NOT NULL DEFAULT '',
  image VARCHAR(500) NOT NULL DEFAULT '',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_categories_mongo_id (mongo_id),
  UNIQUE KEY uq_categories_slug (slug),
  KEY idx_categories_active_gender_type_name (is_active, gender, type, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  mongo_id VARCHAR(24) NULL,
  name VARCHAR(180) NOT NULL,
  slug VARCHAR(220) NOT NULL,
  category_id BIGINT UNSIGNED NULL,
  subcategory VARCHAR(100) NOT NULL DEFAULT '',
  description TEXT NULL,
  tags JSON NULL,
  images JSON NULL,
  primary_image VARCHAR(500) NOT NULL DEFAULT '',
  hover_image VARCHAR(500) NOT NULL DEFAULT '',
  video VARCHAR(500) NOT NULL DEFAULT '',
  gender ENUM('men', 'women') NOT NULL DEFAULT 'men',
  colors JSON NULL,
  sizes JSON NULL,
  original_price DECIMAL(10,2) NULL,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  discount_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
  variants JSON NULL,
  stock INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('draft', 'active', 'out_of_stock', 'archived') NOT NULL DEFAULT 'draft',
  featured TINYINT(1) NOT NULL DEFAULT 0,
  is_trending TINYINT(1) NOT NULL DEFAULT 0,
  is_best_seller TINYINT(1) NOT NULL DEFAULT 0,
  rating DECIMAL(3,2) NOT NULL DEFAULT 0,
  ratings_count INT UNSIGNED NOT NULL DEFAULT 0,
  sales_count INT UNSIGNED NOT NULL DEFAULT 0,
  offer JSON NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_products_mongo_id (mongo_id),
  UNIQUE KEY uq_products_slug (slug),
  KEY idx_products_listing (status, is_deleted, gender, category_id, price, created_at),
  KEY idx_products_flags (is_trending, featured, is_best_seller),
  FULLTEXT KEY ft_products_name_description (name, description),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  mongo_id VARCHAR(24) NULL,
  user_id BIGINT UNSIGNED NULL,
  products JSON NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL DEFAULT 0,
  delivery DECIMAL(10,2) NOT NULL DEFAULT 0,
  gst_percent DECIMAL(5,2) NOT NULL DEFAULT 18,
  gst DECIMAL(10,2) NOT NULL DEFAULT 0,
  discount DECIMAL(10,2) NOT NULL DEFAULT 0,
  total DECIMAL(10,2) NOT NULL DEFAULT 0,
  invoice_number VARCHAR(80) NULL,
  payment_status ENUM('PENDING', 'PAID', 'FAILED') NOT NULL DEFAULT 'PENDING',
  payment_method ENUM('COD', 'ONLINE') NOT NULL DEFAULT 'COD',
  payment JSON NULL,
  status ENUM('placed', 'confirmed', 'processing', 'shipped', 'out_for_delivery', 'delivered', 'cancelled') NOT NULL DEFAULT 'placed',
  status_history JSON NULL,
  shipping_address JSON NOT NULL,
  is_paid TINYINT(1) NOT NULL DEFAULT 0,
  paid_at DATETIME NULL,
  coupon_code VARCHAR(40) NULL,
  shipment JSON NULL,
  shipment_status ENUM('pending', 'booked', 'shipped', 'in_transit', 'delivered') NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_orders_mongo_id (mongo_id),
  UNIQUE KEY uq_orders_invoice_number (invoice_number),
  KEY idx_orders_user_created (user_id, created_at),
  KEY idx_orders_status_created (status, created_at),
  KEY idx_orders_payment_status (payment_status),
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
